INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "А",     "A2\letters\A2L1.png",     "A2\letters\A2L1.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Б",     "A2\letters\A2L2.png",     "A2\letters\A2L2.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "В",     "A2\letters\A2L3.png",     "A2\letters\A2L3.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Г",     "A2\letters\A2L4.png",     "A2\letters\A2L4.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Д",     "A2\letters\A2L5.png",     "A2\letters\A2L5.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Е",     "A2\letters\A2L6.png",     "A2\letters\A2L6.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ё",     "A2\letters\A2L7.png",     "A2\letters\A2L7.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ж",     "A2\letters\A2L8.png",     "A2\letters\A2L8.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "З",     "A2\letters\A2L9.png",     "A2\letters\A2L9.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "И",     "A2\letters\A2L10.png",     "A2\letters\A2L10.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Й",     "A2\letters\A2L11.png",     "A2\letters\A2L11.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "К",     "A2\letters\A2L12.png",     "A2\letters\A2L12.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Л",     "A2\letters\A2L13.png",     "A2\letters\A2L13.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "М",     "A2\letters\A2L14.png",     "A2\letters\A2L14.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Н",     "A2\letters\A2L15.png",     "A2\letters\A2L15.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "О",     "A2\letters\A2L16.png",     "A2\letters\A2L16.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "П",     "A2\letters\A2L17.png",     "A2\letters\A2L17.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Р",     "A2\letters\A2L18.png",     "A2\letters\A2L18.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "С",     "A2\letters\A2L19.png",     "A2\letters\A2L19.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Т",     "A2\letters\A2L20.png",     "A2\letters\A2L20.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "У",     "A2\letters\A2L21.png",     "A2\letters\A2L21.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ф",     "A2\letters\A2L22.png",     "A2\letters\A2L22.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Х",     "A2\letters\A2L23.png",     "A2\letters\A2L23.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ц",     "A2\letters\A2L24.png",     "A2\letters\A2L24.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ч",     "A2\letters\A2L25.png",     "A2\letters\A2L25.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ш",     "A2\letters\A2L26.png",     "A2\letters\A2L26.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Щ",     "A2\letters\A2L27.png",     "A2\letters\A2L27.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ъ",     "A2\letters\A2L28.png",     "A2\letters\A2L28.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ы",     "A2\letters\A2L29.png",     "A2\letters\A2L29.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ь",     "A2\letters\A2L30.png",     "A2\letters\A2L30.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Э",     "A2\letters\A2L31.png",     "A2\letters\A2L31.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Ю",     "A2\letters\A2L32.png",     "A2\letters\A2L32.wav"  );
INSERT INTO [Letter] (AlphabetID,     Value,     Logo,     Sound) VALUES ( 2,     "Я",     "A2\letters\A2L33.png",     "A2\letters\A2L33.wav"  );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  28,       2,       "A2\words\A2L1W1P.png",       "A2\words\A2L1W1A.wav",       "A2\words\A2L1W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  29,       2,       "A2\words\A2L2W1P.png",       "A2\words\A2L2W1A.wav",       "A2\words\A2L2W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  30,       2,       "A2\words\A2L3W1P.png",       "A2\words\A2L3W1A.wav",       "A2\words\A2L3W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  31,       2,       "A2\words\A2L4W1P.png",       "A2\words\A2L4W1A.wav",       "A2\words\A2L4W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  32,       2,       "A2\words\A2L5W1P.png",       "A2\words\A2L5W1A.wav",       "A2\words\A2L5W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  33,       2,       "A2\words\A2L6W1P.png",       "A2\words\A2L6W1A.wav",       "A2\words\A2L6W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  34,       2,       "A2\words\A2L7W1P.png",       "A2\words\A2L7W1A.wav",       "A2\words\A2L7W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  35,       2,       "A2\words\A2L8W1P.png",       "A2\words\A2L8W1A.wav",       "A2\words\A2L8W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  36,       2,       "A2\words\A2L9W1P.png",       "A2\words\A2L9W1A.wav",       "A2\words\A2L9W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  37,       2,       "A2\words\A2L10W1P.png",       "A2\words\A2L10W1A.wav",       "A2\words\A2L10W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  39,       2,       "A2\words\A2L12W1P.png",       "A2\words\A2L12W1A.wav",       "A2\words\A2L12W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  40,       2,       "A2\words\A2L13W1P.png",       "A2\words\A2L13W1A.wav",       "A2\words\A2L13W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  41,       2,       "A2\words\A2L14W1P.png",       "A2\words\A2L14W1A.wav",       "A2\words\A2L14W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  42,       2,       "A2\words\A2L15W1P.png",       "A2\words\A2L15W1A.wav",       "A2\words\A2L15W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  43,       2,       "A2\words\A2L16W1P.png",       "A2\words\A2L16W1A.wav",       "A2\words\A2L16W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  44,       2,       "A2\words\A2L17W1P.png",       "A2\words\A2L17W1A.wav",       "A2\words\A2L17W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  45,       2,       "A2\words\A2L18W1P.png",       "A2\words\A2L18W1A.wav",       "A2\words\A2L18W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  46,       2,       "A2\words\A2L19W1P.png",       "A2\words\A2L19W1A.wav",       "A2\words\A2L19W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  47,       2,       "A2\words\A2L20W1P.png",       "A2\words\A2L20W1A.wav",       "A2\words\A2L20W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  48,       2,       "A2\words\A2L21W1P.png",       "A2\words\A2L21W1A.wav",       "A2\words\A2L21W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  49,       2,       "A2\words\A2L22W1P.png",       "A2\words\A2L22W1A.wav",       "A2\words\A2L22W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  50,       2,       "A2\words\A2L23W1P.png",       "A2\words\A2L23W1A.wav",       "A2\words\A2L23W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  51,       2,       "A2\words\A2L24W1P.png",       "A2\words\A2L24W1A.wav",       "A2\words\A2L24W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  52,       2,       "A2\words\A2L25W1P.png",       "A2\words\A2L25W1A.wav",       "A2\words\A2L25W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  53,       2,       "A2\words\A2L26W1P.png",       "A2\words\A2L26W1A.wav",       "A2\words\A2L26W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  54,       2,       "A2\words\A2L27W1P.png",       "A2\words\A2L27W1A.wav",       "A2\words\A2L27W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  58,       2,       "A2\words\A2L31W1P.png",       "A2\words\A2L31W1A.wav",       "A2\words\A2L31W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  60,       2,       "A2\words\A2L33W1P.png",       "A2\words\A2L33W1A.wav",       "A2\words\A2L33W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  59,       2,       "A2\words\A2L32W1P.png",       "A2\words\A2L32W1A.wav",       "A2\words\A2L32W1.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  28,       2,       "A2\words\A2L1W2P.png",       "A2\words\A2L1W2A.wav",       "A2\words\A2L1W2.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  30,       2,       "A2\words\A2L3W2P.png",       "A2\words\A2L3W2A.wav",       "A2\words\A2L3W2.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  30,       2,       "A2\words\A2L3W3P.png",       "A2\words\A2L3W3A.wav",       "A2\words\A2L3W3.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  32,       2,       "A2\words\A2L5W2P.png",       "A2\words\A2L5W2A.wav",       "A2\words\A2L5W2.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  36,       2,       "A2\words\A2L9W2P.png",       "A2\words\A2L9W2A.wav",       "A2\words\A2L9W2.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  36,       2,       "A2\words\A2L9W3P.png",       "A2\words\A2L9W3A.wav",       "A2\words\A2L9W3.png" );
  INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES (  37,       2,       "A2\words\A2L10W2P.png",       "A2\words\A2L10W2A.wav",       "A2\words\A2L10W2.png" );
  INSERT INTO [Alphabet] (Logo) VALUES ( "A2/A2logo.png") ;