INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "A",   "A1\letters\A1L1.png",   "A1\letters\A1L1A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "B",   "A1\letters\A1L2.png",   "A1\letters\A1L2A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "C",   "A1\letters\A1L3.png",   "A1\letters\A1L3A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "D",   "A1\letters\A1L4.png",   "A1\letters\A1L4A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "E",   "A1\letters\A1L5.png",   "A1\letters\A1L5A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "F",   "A1\letters\A1L6.png",   "A1\letters\A1L6A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "G",   "A1\letters\A1L7.png",   "A1\letters\A1L7A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "H",   "A1\letters\A1L8.png",   "A1\letters\A1L8A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "I",   "A1\letters\A1L9.png",   "A1\letters\A1L9A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "J",   "A1\letters\A1L10.png",   "A1\letters\A1L10A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "K",   "A1\letters\A1L11.png",   "A1\letters\A1L11A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "L",   "A1\letters\A1L12.png",   "A1\letters\A1L12A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "M",   "A1\letters\A1L13.png",   "A1\letters\A1L13A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "N",   "A1\letters\A1L14.png",   "A1\letters\A1L14A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "O",   "A1\letters\A1L15.png",   "A1\letters\A1L15A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "P",   "A1\letters\A1L16.png",   "A1\letters\A1L16A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "Q",   "A1\letters\A1L17.png",   "A1\letters\A1L17A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "R",   "A1\letters\A1L18.png",   "A1\letters\A1L18A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "S",   "A1\letters\A1L19.png",   "A1\letters\A1L19A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "T",   "A1\letters\A1L20.png",   "A1\letters\A1L20A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "U",   "A1\letters\A1L21.png",   "A1\letters\A1L21A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "V",   "A1\letters\A1L22.png",   "A1\letters\A1L22A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "W",   "A1\letters\A1L23.png",   "A1\letters\A1L23A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "X",   "A1\letters\A1L24.png",   "A1\letters\A1L24A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "Y",   "A1\letters\A1L25.png",   "A1\letters\A1L25A.mp3" );
INSERT INTO [Letter](AlphabetID,   Value,   Logo,   Sound) VALUES ( 1,   "Z",   "A1\letters\A1L26.png",   "A1\letters\A1L26A.mp3" );
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W1P.png",     "A1\words\A1L1W1A.mp3",     "A1\words\A1L1W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W2P.png",     "A1\words\A1L1W2A.mp3",     "A1\words\A1L1W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W3P.png",     "A1\words\A1L1W3A.mp3",     "A1\words\A1L1W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W1P.png",     "A1\words\A1L2W1A.mp3",     "A1\words\A1L2W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W2P.png",     "A1\words\A1L2W2A.mp3",     "A1\words\A1L2W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 3,     1,     "A1\words\A1L3W1P.png",     "A1\words\A1L3W1A.mp3",     "A1\words\A1L3W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 3,     1,     "A1\words\A1L3W2P.png",     "A1\words\A1L3W2A.mp3",     "A1\words\A1L3W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W1P.png",     "A1\words\A1L4W1A.mp3",     "A1\words\A1L4W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W2P.png",     "A1\words\A1L4W2A.mp3",     "A1\words\A1L4W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 5,     1,     "A1\words\A1L5W1P.png",     "A1\words\A1L5W1A.mp3",     "A1\words\A1L5W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 5,     1,     "A1\words\A1L5W2P.png",     "A1\words\A1L5W2A.mp3",     "A1\words\A1L5W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 6,     1,     "A1\words\A1L6W1P.png",     "A1\words\A1L6W1A.mp3",     "A1\words\A1L6W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 6,     1,     "A1\words\A1L6W2P.png",     "A1\words\A1L6W2A.mp3",     "A1\words\A1L6W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 7,     1,     "A1\words\A1L7W1P.png",     "A1\words\A1L7W1A.mp3",     "A1\words\A1L7W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 7,     1,     "A1\words\A1L7W2P.png",     "A1\words\A1L7W2A.mp3",     "A1\words\A1L7W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 8,     1,     "A1\words\A1L8W1P.png",     "A1\words\A1L8W1A.mp3",     "A1\words\A1L8W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 8,     1,     "A1\words\A1L8W2P.png",     "A1\words\A1L8W2A.mp3",     "A1\words\A1L8W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 9,     1,     "A1\words\A1L9W1P.png",     "A1\words\A1L9W1A.mp3",     "A1\words\A1L9W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 9,     1,     "A1\words\A1L9W2P.png",     "A1\words\A1L9W2A.mp3",     "A1\words\A1L9W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 16,     1,     "A1\words\A1L16W1P.png",     "A1\words\A1L16W1A.mp3",     "A1\words\A1L16W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 15,     1,     "A1\words\A1L15W2P.png",     "A1\words\A1L15W2A.mp3",     "A1\words\A1L15W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 11,     1,     "A1\words\A1L11W1P.png",     "A1\words\A1L11W1A.mp3",     "A1\words\A1L11W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 10,     1,     "A1\words\A1L10W2P.png",     "A1\words\A1L10W2A.mp3",     "A1\words\A1L10W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 15,     1,     "A1\words\A1L15W1P.png",     "A1\words\A1L15W1A.mp3",     "A1\words\A1L15W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 14,     1,     "A1\words\A1L14W1P.png",     "A1\words\A1L14W1A.mp3",     "A1\words\A1L14W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 13,     1,     "A1\words\A1L13W2P.png",     "A1\words\A1L13W2A.mp3",     "A1\words\A1L13W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 13,     1,     "A1\words\A1L13W1P.png",     "A1\words\A1L13W1A.mp3",     "A1\words\A1L13W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 12,     1,     "A1\words\A1L12W2P.png",     "A1\words\A1L12W2A.mp3",     "A1\words\A1L12W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 12,     1,     "A1\words\A1L12W1P.png",     "A1\words\A1L12W1A.mp3",     "A1\words\A1L12W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 11,     1,     "A1\words\A1L11W2P.png",     "A1\words\A1L11W2A.mp3",     "A1\words\A1L11W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 16,     1,     "A1\words\A1L16W3P.png",     "A1\words\A1L16W3A.mp3",     "A1\words\A1L16W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 17,     1,     "A1\words\A1L17W1P.png",     "A1\words\A1L17W1A.mp3",     "A1\words\A1L17W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 17,     1,     "A1\words\A1L17W2P.png",     "A1\words\A1L17W2A.mp3",     "A1\words\A1L17W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 17,     1,     "A1\words\A1L17W3P.png",     "A1\words\A1L17W3A.mp3",     "A1\words\A1L17W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W1P.png",     "A1\words\A1L18W1A.mp3",     "A1\words\A1L18W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W1P.png",     "A1\words\A1L19W1A.mp3",     "A1\words\A1L19W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W2P.png",     "A1\words\A1L19W2A.mp3",     "A1\words\A1L19W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W1P.png",     "A1\words\A1L20W1A.mp3",     "A1\words\A1L20W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W2P.png",     "A1\words\A1L20W2A.mp3",     "A1\words\A1L20W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 21,     1,     "A1\words\A1L21W1P.png",     "A1\words\A1L21W1A.mp3",     "A1\words\A1L21W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 21,     1,     "A1\words\A1L21W2P.png",     "A1\words\A1L21W2A.mp3",     "A1\words\A1L21W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 22,     1,     "A1\words\A1L22W1P.png",     "A1\words\A1L22W1A.mp3",     "A1\words\A1L22W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 22,     1,     "A1\words\A1L22W2P.png",     "A1\words\A1L22W2A.mp3",     "A1\words\A1L22W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W2P.png",     "A1\words\A1L23W2A.mp3",     "A1\words\A1L23W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 24,     1,     "A1\words\A1L24W1P.png",     "A1\words\A1L24W1A.mp3",     "A1\words\A1L24W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 25,     1,     "A1\words\A1L25W1P.png",     "A1\words\A1L25W1A.mp3",     "A1\words\A1L25W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 26,     1,     "A1\words\A1L26W1P.png",     "A1\words\A1L26W1A.mp3",     "A1\words\A1L26W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W4P.png",     "A1\words\A1L1W4A.mp3",     "A1\words\A1L1W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W5P.png",     "A1\words\A1L1W5A.mp3",     "A1\words\A1L1W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 1,     1,     "A1\words\A1L1W6P.png",     "A1\words\A1L1W6A.mp3",     "A1\words\A1L1W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W3P.png",     "A1\words\A1L2W3A.mp3",     "A1\words\A1L2W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W4P.png",     "A1\words\A1L2W4A.mp3",     "A1\words\A1L2W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W5P.png",     "A1\words\A1L2W5A.mp3",     "A1\words\A1L2W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 2,     1,     "A1\words\A1L2W6P.png",     "A1\words\A1L2W6A.mp3",     "A1\words\A1L2W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 3,     1,     "A1\words\A1L3W3P.png",     "A1\words\A1L3W3A.mp3",     "A1\words\A1L3W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 3,     1,     "A1\words\A1L3W4P.png",     "A1\words\A1L3W4A.mp3",     "A1\words\A1L3W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 3,     1,     "A1\words\A1L3W5P.png",     "A1\words\A1L3W5A.mp3",     "A1\words\A1L3W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W3P.png",     "A1\words\A1L4W3A.mp3",     "A1\words\A1L4W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W4P.png",     "A1\words\A1L4W4A.mp3",     "A1\words\A1L4W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W5P.png",     "A1\words\A1L4W5A.mp3",     "A1\words\A1L4W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 4,     1,     "A1\words\A1L4W6P.png",     "A1\words\A1L4W6A.mp3",     "A1\words\A1L4W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 5,     1,     "A1\words\A1L5W3P.png",     "A1\words\A1L5W3A.mp3",     "A1\words\A1L5W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 5,     1,     "A1\words\A1L5W4P.png",     "A1\words\A1L5W4A.mp3",     "A1\words\A1L5W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 5,     1,     "A1\words\A1L5W5P.png",     "A1\words\A1L5W5A.mp3",     "A1\words\A1L5W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 6,     1,     "A1\words\A1L6W4P.png",     "A1\words\A1L6W4A.mp3",     "A1\words\A1L6W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 6,     1,     "A1\words\A1L6W3P.png",     "A1\words\A1L6W3A.mp3",     "A1\words\A1L6W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 7,     1,     "A1\words\A1L7W3P.png",     "A1\words\A1L7W3A.mp3",     "A1\words\A1L7W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 7,     1,     "A1\words\A1L7W4P.png",     "A1\words\A1L7W4A.mp3",     "A1\words\A1L7W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 7,     1,     "A1\words\A1L7W5P.png",     "A1\words\A1L7W5A.mp3",     "A1\words\A1L7W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 8,     1,     "A1\words\A1L8W3P.png",     "A1\words\A1L8W3A.mp3",     "A1\words\A1L8W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 8,     1,     "A1\words\A1L8W4P.png",     "A1\words\A1L8W4A.mp3",     "A1\words\A1L8W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 8,     1,     "A1\words\A1L8W5P.png",     "A1\words\A1L8W5A.mp3",     "A1\words\A1L8W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 9,     1,     "A1\words\A1L9W3P.png",     "A1\words\A1L9W3A.mp3",     "A1\words\A1L9W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 9,     1,     "A1\words\A1L9W4P.png",     "A1\words\A1L9W4A.mp3",     "A1\words\A1L9W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 10,     1,     "A1\words\A1L10W1P.png",     "A1\words\A1L10W1A.mp3",     "A1\words\A1L10W1.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 10,     1,     "A1\words\A1L10W3P.png",     "A1\words\A1L10W3A.mp3",     "A1\words\A1L10W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 10,     1,     "A1\words\A1L10W4P.png",     "A1\words\A1L10W4A.mp3",     "A1\words\A1L10W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 11,     1,     "A1\words\A1L11W3P.png",     "A1\words\A1L11W3A.mp3",     "A1\words\A1L11W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 11,     1,     "A1\words\A1L11W4P.png",     "A1\words\A1L11W4A.mp3",     "A1\words\A1L11W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 12,     1,     "A1\words\A1L12W3P.png",     "A1\words\A1L12W3A.mp3",     "A1\words\A1L12W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 12,     1,     "A1\words\A1L12W4P.png",     "A1\words\A1L12W4A.mp3",     "A1\words\A1L12W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 13,     1,     "A1\words\A1L13W3P.png",     "A1\words\A1L13W3A.mp3",     "A1\words\A1L13W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 13,     1,     "A1\words\A1L13W4P.png",     "A1\words\A1L13W4A.mp3",     "A1\words\A1L13W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 13,     1,     "A1\words\A1L13W5P.png",     "A1\words\A1L13W5A.mp3",     "A1\words\A1L13W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 14,     1,     "A1\words\A1L14W2P.png",     "A1\words\A1L14W2A.mp3",     "A1\words\A1L14W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 14,     1,     "A1\words\A1L14W3P.png",     "A1\words\A1L14W3A.mp3",     "A1\words\A1L14W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 14,     1,     "A1\words\A1L14W4P.png",     "A1\words\A1L14W4A.mp3",     "A1\words\A1L14W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 15,     1,     "A1\words\A1L15W3P.png",     "A1\words\A1L15W3A.mp3",     "A1\words\A1L15W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 15,     1,     "A1\words\A1L15W4P.png",     "A1\words\A1L15W4A.mp3",     "A1\words\A1L15W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 15,     1,     "A1\words\A1L15W5P.png",     "A1\words\A1L15W5A.mp3",     "A1\words\A1L15W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 16,     1,     "A1\words\A1L16W2P.png",     "A1\words\A1L16W2A.mp3",     "A1\words\A1L16W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 16,     1,     "A1\words\A1L16W4P.png",     "A1\words\A1L16W4A.mp3",     "A1\words\A1L16W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 16,     1,     "A1\words\A1L16W5P.png",     "A1\words\A1L16W5A.mp3",     "A1\words\A1L16W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W2P.png",     "A1\words\A1L18W2A.mp3",     "A1\words\A1L18W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W3P.png",     "A1\words\A1L18W3A.mp3",     "A1\words\A1L18W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W4P.png",     "A1\words\A1L18W4A.mp3",     "A1\words\A1L18W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W5P.png",     "A1\words\A1L18W5A.mp3",     "A1\words\A1L18W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 18,     1,     "A1\words\A1L18W6P.png",     "A1\words\A1L18W6A.mp3",     "A1\words\A1L18W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W6P.png",     "A1\words\A1L19W6A.mp3",     "A1\words\A1L19W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W5P.png",     "A1\words\A1L19W5A.mp3",     "A1\words\A1L19W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W4P.png",     "A1\words\A1L19W4A.mp3",     "A1\words\A1L19W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 19,     1,     "A1\words\A1L19W3P.png",     "A1\words\A1L19W3A.mp3",     "A1\words\A1L19W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W3P.png",     "A1\words\A1L20W3A.mp3",     "A1\words\A1L20W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W4P.png",     "A1\words\A1L20W4A.mp3",     "A1\words\A1L20W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W5P.png",     "A1\words\A1L20W5A.mp3",     "A1\words\A1L20W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 20,     1,     "A1\words\A1L20W6P.png",     "A1\words\A1L20W6A.mp3",     "A1\words\A1L20W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 21,     1,     "A1\words\A1L21W3P.png",     "A1\words\A1L21W3A.mp3",     "A1\words\A1L21W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 22,     1,     "A1\words\A1L22W3P.png",     "A1\words\A1L22W3A.mp3",     "A1\words\A1L22W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 22,     1,     "A1\words\A1L22W4P.png",     "A1\words\A1L22W4A.mp3",     "A1\words\A1L22W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 22,     1,     "A1\words\A1L22W5P.png",     "A1\words\A1L22W5A.mp3",     "A1\words\A1L22W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W3P.png",     "A1\words\A1L23W3A.mp3",     "A1\words\A1L23W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W4P.png",     "A1\words\A1L23W4A.mp3",     "A1\words\A1L23W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W5P.png",     "A1\words\A1L23W5A.mp3",     "A1\words\A1L23W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W6P.png",     "A1\words\A1L23W6A.mp3",     "A1\words\A1L23W6.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 23,     1,     "A1\words\A1L23W7P.png",     "A1\words\A1L23W7A.mp3",     "A1\words\A1L23W7.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 24,     1,     "A1\words\A1L24W2P.png",     "A1\words\A1L24W2A.mp3",     "A1\words\A1L24W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 25,     1,     "A1\words\A1L25W5P.png",     "A1\words\A1L25W5A.mp3",     "A1\words\A1L25W5.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 25,     1,     "A1\words\A1L25W4P.png",     "A1\words\A1L25W4A.mp3",     "A1\words\A1L25W4.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 25,     1,     "A1\words\A1L25W3P.png",     "A1\words\A1L25W3A.mp3",     "A1\words\A1L25W3.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 25,     1,     "A1\words\A1L25W2P.png",     "A1\words\A1L25W2A.mp3",     "A1\words\A1L25W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 26,     1,     "A1\words\A1L26W2P.png",     "A1\words\A1L26W2A.mp3",     "A1\words\A1L26W2.png" );  
 INSERT INTO [Word] ( LetterID,     AlphabetID,     Image,     Sound,     ValueImg ) VALUES ( 26,     1,     "A1\words\A1L26W3P.png",     "A1\words\A1L26W3A.mp3",     "A1\words\A1L26W3.png" );
 INSERT INTO [AlphabetLocalization]( AlphabetID,     LanguageID,     LanguageName,     Description ) VALUES ( 1,     "ru-RU",     "Английский",     "Изучай английский алфавит весело!"  );
 INSERT INTO [AlphabetLocalization]( AlphabetID,     LanguageID,     LanguageName,     Description ) VALUES ( 1,     "en-US",     "English",     "Learn ABC with fun!"  );
 INSERT INTO [Alphabet] (Logo) VALUES ( "A1/logo.png");